-- Supabase/PostgreSQL schema for Fut - Amigos do FMR
create extension if not exists pgcrypto;

create table if not exists public.leagues (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  logo_url text,
  season text not null default '2025',
  match_date date,
  match_time time,
  venue text,
  duration_minutes integer not null default 8 check (duration_minutes in (8, 10)),
  venue_latitude double precision,
  venue_longitude double precision,
  venue_radius_meters integer default 150,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.league_members (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  auth_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  nickname text not null,
  email text,
  position text not null check (position in ('GOL','DEF','MEI','ATA')),
  monthly boolean not null default false,
  is_admin boolean not null default false,
  is_referee boolean not null default false,
  availability text not null default 'available' check (availability in ('available','indisponível','DM')),
  avatar_url text,
  presence integer not null default 0,
  goals integer not null default 0,
  assists integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  cards integer not null default 0,
  rating numeric(4,2) not null default 6.5,
  created_at timestamptz not null default now(),
  unique (league_id, nickname)
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  match_number integer not null,
  status text not null default 'aguardando rolar',
  score_blue integer not null default 0,
  score_red integer not null default 0,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  member_id bigint references public.league_members(id) on delete set null,
  type text not null check (type in ('Gol','Assistência','Cartão','Substituição')),
  detail text not null,
  event_time text not null,
  tone text not null default 'slate',
  created_at timestamptz not null default now()
);

create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  member_id bigint not null references public.league_members(id) on delete cascade,
  match_date date not null,
  checked_in_at timestamptz not null default now(),
  latitude double precision,
  longitude double precision,
  distance_meters double precision,
  unique (league_id, member_id, match_date)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  title text not null,
  message text not null,
  category text not null check (category in ('jogo','check-in','escala','administração')),
  created_at timestamptz not null default now()
);

create table if not exists public.notification_reads (
  notification_id bigint not null references public.notifications(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, auth_user_id)
);

alter table public.leagues enable row level security;
alter table public.league_members enable row level security;
alter table public.matches enable row level security;
alter table public.match_events enable row level security;
alter table public.checkins enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;

create policy "league members can read their leagues" on public.leagues for select using (exists (select 1 from public.league_members m where m.league_id = leagues.id and m.auth_user_id = auth.uid()));
create policy "league members can read members" on public.league_members for select using (exists (select 1 from public.league_members mine where mine.league_id = league_members.league_id and mine.auth_user_id = auth.uid()));
create policy "admins can manage members" on public.league_members for all using (exists (select 1 from public.league_members mine where mine.league_id = league_members.league_id and mine.auth_user_id = auth.uid() and mine.is_admin));
create policy "members can read matches" on public.matches for select using (exists (select 1 from public.league_members m where m.league_id = matches.league_id and m.auth_user_id = auth.uid()));
create policy "members can read events" on public.match_events for select using (exists (select 1 from public.matches mt join public.league_members m on m.league_id = mt.league_id where mt.id = match_events.match_id and m.auth_user_id = auth.uid()));
create policy "members can read notifications" on public.notifications for select using (exists (select 1 from public.league_members m where m.league_id = notifications.league_id and m.auth_user_id = auth.uid()));
create policy "users manage their reads" on public.notification_reads for all using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());
create policy "members can read checkins" on public.checkins for select using (exists (select 1 from public.league_members m where m.league_id = checkins.league_id and m.auth_user_id = auth.uid()));
create policy "users insert own checkin" on public.checkins for insert with check (exists (select 1 from public.league_members m where m.id = checkins.member_id and m.auth_user_id = auth.uid()));
